### ISSUE TITLE
Types are missing

### ISSUE THREAD

**Issue by ogliznutsa** [wangweiwei/video-metadata-thumbnails#1]
Hi,

The package is written using Typescript but it doesn't provide TypeScript definitions.

**Comment by stackbug** [comment]
It has been fixed in `video-metadata-thumbnails@1.0.8`, please try it again.

**Comment by wangweiwei** [comment]
It has been fixed in `video-metadata-thumbnails@1.0.8`, please try it again.

**Comment by ogliznutsa** [comment]
TypeScript definitions are in place, thanks!
