### ISSUE TITLE
Unable to get the single thumbnail of the first frame 

### ISSUE THREAD

**Issue by ogliznutsa** [wangweiwei/video-metadata-thumbnails#2]
Hi,

`getThumbnails()` with `{  start: 0, end: 0 }` options returns thumbnails for each second of video duration instead of the first frame. It is impossible to get the thumbnail of the first frame without getting all the thumbnails.

**Comment by wangweiwei** [comment]
It has been fixed in `video-metadata-thumbnails@1.0.8`, please try it again.

**Comment by ogliznutsa** [comment]
Now it works, thanks for a quick fix!
